name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - run: npm ci # or yarn install

      - uses: wearerequired/lint-action@v2        
        with:
          eslint: true
          prettier: false
          eslint_dir: node_modules/eslint/bin/
          eslint_args: "--ignore-path .eslintignore src"
